name: Build DayEntryApp Without CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using GCC/Clang
      run: |
        g++ -o DayEntryApp main.cpp DayEntryApp.cpp

    - name: Run the application
      run: ./DayEntryApp
